import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });

  const supabase = createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
  );

  // Verify admin
  const authHeader = req.headers.get("Authorization");
  if (!authHeader) return new Response("Unauthorized", { status: 401, headers: corsHeaders });
  const token = authHeader.replace("Bearer ", "");
  const { data: { user } } = await supabase.auth.getUser(token);
  if (!user) return new Response("Unauthorized", { status: 401, headers: corsHeaders });
  const { data: roles } = await supabase.from("user_roles").select("role").eq("user_id", user.id);
  if (!roles?.some((r: any) => r.role === "admin")) return new Response("Forbidden", { status: 403, headers: corsHeaders });

  // Check if already seeded
  const { count } = await supabase.from("major_categories").select("*", { count: "exact", head: true });
  if ((count ?? 0) > 0) {
    return new Response(JSON.stringify({ message: "Already seeded", count }), { headers: { ...corsHeaders, "Content-Type": "application/json" } });
  }

  const categories = [
    { title_ar: "العلوم الصحية والطبية", title_en: "Health & Medical Sciences", sort_order: 0 },
    { title_ar: "الهندسة والتكنولوجيا", title_en: "Engineering & Technology", sort_order: 1 },
    { title_ar: "إدارة الأعمال والاقتصاد", title_en: "Business & Economics", sort_order: 2 },
    { title_ar: "العلوم الاجتماعية والإنسانية", title_en: "Social Sciences & Humanities", sort_order: 3 },
    { title_ar: "العلوم الطبيعية والرياضيات", title_en: "Natural Sciences & Mathematics", sort_order: 4 },
  ];

  const { data: cats, error: catErr } = await supabase.from("major_categories").insert(categories).select();
  if (catErr) return new Response(JSON.stringify({ error: catErr.message }), { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } });

  const catMap: Record<string, string> = {};
  cats!.forEach((c: any) => { catMap[c.title_en] = c.id; });

  // Health majors
  const healthMajors = [
    { name_ar: "الصحة العامة", name_en: "Public Health", description_ar: "تعرف على تخصص الصحة العامة وتحسين صحة المجتمعات", description_en: "Learn about public health and improving community wellness", duration_ar: "6 فصول دراسية", duration_en: "6 semesters", suitable_for_ar: "الطلاب المهتمين بصحة المجتمع والوقاية من الأمراض", suitable_for_en: "Students interested in community health and disease prevention", required_background_ar: "شهادة بجروت مع تركيز على العلوم (أحياء، كيمياء)", required_background_en: "Bagrut certificate with focus on sciences (biology, chemistry)", language_requirements_ar: "B2 ألماني لمعظم البرامج", language_requirements_en: "B2 German for most programs, some available in English", career_opportunities_ar: "وظائف في وزارات الصحة، منظمة الصحة العالمية، شركات التأمين الصحي", career_opportunities_en: "Positions at health ministries, WHO, health insurance companies", arab48_notes_ar: "تخصص مناسب جداً. شهادة البجروت كافية للقبول المباشر", arab48_notes_en: "Very suitable. Bagrut certificate sufficient for direct admission", sort_order: 0 },
    { name_ar: "المعلوماتية الحيوية", name_en: "Bioinformatics", description_ar: "اكتشف دور الحوسبة في تحليل البيانات الحيوية", description_en: "Discover the role of computing in analyzing biological data", duration_ar: "6 فصول دراسية", duration_en: "6 semesters", suitable_for_ar: "الطلاب الذين يجمعون بين حب البرمجة والعلوم الحيوية", suitable_for_en: "Students combining programming and biological sciences", required_background_ar: "بجروت مع 4-5 وحدات رياضيات وتركيز على العلوم", required_background_en: "Bagrut with 4-5 units math and science focus", language_requirements_ar: "B2 ألماني أو IELTS 6.5 للبرامج الإنجليزية", language_requirements_en: "B2 German or IELTS 6.5 for English programs", career_opportunities_ar: "شركات مثل BioNTech، CureVac، Bayer. رواتب 45,000-55,000 يورو", career_opportunities_en: "Companies like BioNTech, CureVac, Bayer. Salaries 45,000-55,000 EUR", arab48_notes_ar: "معدل بجروت 70+ كافٍ. فرص عمل واسعة", arab48_notes_en: "Bagrut GPA 70+ sufficient. Wide job opportunities", sort_order: 1 },
    { name_ar: "الهندسة الطبية الحيوية", name_en: "Biomedical Engineering", description_ar: "اجمع بين الطب والهندسة", description_en: "Combine medicine and engineering", duration_ar: "6 فصول دراسية", duration_en: "6 semesters", suitable_for_ar: "الطلاب المهتمين بالتكنولوجيا والطب", suitable_for_en: "Students interested in technology and medicine", required_background_ar: "بجروت مع 4-5 وحدات رياضيات وفيزياء", required_background_en: "Bagrut with 4-5 units math and physics", language_requirements_ar: "B2 ألماني لمعظم البرامج", language_requirements_en: "B2 German for most programs", career_opportunities_ar: "شركات مثل Siemens Healthineers. رواتب 48,000-58,000 يورو", career_opportunities_en: "Companies like Siemens Healthineers. Salaries 48,000-58,000 EUR", arab48_notes_ar: "شهادة البجروت مقبولة للتقديم المباشر بمعدل فوق 65", arab48_notes_en: "Bagrut accepted for direct admission with GPA above 65", sort_order: 2 },
    { name_ar: "الصيدلة", name_en: "Pharmacy", description_ar: "اكتشف علم الأدوية وتطوير العلاجات", description_en: "Discover pharmacology and treatment development", duration_ar: "8 فصول دراسية", duration_en: "8 semesters", suitable_for_ar: "الطلاب الذين يحبون الكيمياء والأحياء", suitable_for_en: "Students who love chemistry and biology", required_background_ar: "بجروت بمعدل 75+ مع تركيز على الكيمياء والأحياء", required_background_en: "Bagrut with GPA 75+ focusing on chemistry and biology", language_requirements_ar: "C1 ألماني إلزامي", language_requirements_en: "C1 German mandatory", career_opportunities_ar: "نقص كبير في الصيادلة. راتب 3,800-4,500 يورو شهرياً", career_opportunities_en: "Major pharmacist shortage. Salary 3,800-4,500 EUR/month", arab48_notes_ar: "يتطلب ألمانية قوية جداً (C1). معدل بجروت 75+ مطلوب", arab48_notes_en: "Requires very strong German (C1). Bagrut GPA 75+ required", sort_order: 3 },
    { name_ar: "طب الأسنان", name_en: "Dentistry", description_ar: "تعرف على مسار طب الأسنان", description_en: "Learn about the dentistry pathway", duration_ar: "10 فصول دراسية", duration_en: "10 semesters", suitable_for_ar: "الطلاب ذوي المعدلات العالية والمهارات اليدوية الدقيقة", suitable_for_en: "Students with high grades and precise manual skills", required_background_ar: "بجروت بمعدل 85+ مع 5 وحدات في العلوم الطبيعية", required_background_en: "Bagrut with GPA 85+ and 5 units in natural sciences", language_requirements_ar: "C1 ألماني إلزامي", language_requirements_en: "C1 German mandatory", career_opportunities_ar: "نقص كبير في أطباء الأسنان. راتب 4,000-5,000 يورو", career_opportunities_en: "Major dentist shortage. Salary 4,000-5,000 EUR", arab48_notes_ar: "يتطلب معدل بجروت عالٍ جداً", arab48_notes_en: "Requires very high Bagrut GPA", sort_order: 4 },
    { name_ar: "الطب", name_en: "Medicine", description_ar: "اكتشف مجال الطب وفرصه المستقبلية", description_en: "Discover the field of medicine", duration_ar: "12 فصل دراسي + سنة تدريب", duration_en: "12 semesters + 1 practical year", suitable_for_ar: "الطلاب ذوي المعدلات العالية جداً (90+)", suitable_for_en: "Students with very high GPA (90+)", required_background_ar: "بجروت بمعدل 90+ مع 5 وحدات في الأحياء والكيمياء", required_background_en: "Bagrut with GPA 90+ and 5 units in biology and chemistry", language_requirements_ar: "C1 ألماني إلزامي", language_requirements_en: "C1 German mandatory", career_opportunities_ar: "نقص حاد في الأطباء. راتب 4,500-5,500 يورو شهرياً", career_opportunities_en: "Severe doctor shortage. Salary 4,500-5,500 EUR/month", arab48_notes_ar: "أصعب التخصصات للقبول. معدل فوق 90 مطلوب", arab48_notes_en: "Hardest major for admission. GPA above 90 required", sort_order: 5 },
    { name_ar: "العلاج الطبيعي", name_en: "Physiotherapy", description_ar: "تعرف على تخصص العلاج الطبيعي", description_en: "Learn about physiotherapy", duration_ar: "6 فصول دراسية", duration_en: "6 semesters", suitable_for_ar: "الطلاب الرياضيين المهتمين بالصحة البدنية", suitable_for_en: "Athletic students interested in physical health", required_background_ar: "بجروت بمعدل 60+", required_background_en: "Bagrut with GPA 60+", language_requirements_ar: "B2 ألماني إلزامي", language_requirements_en: "B2 German mandatory", career_opportunities_ar: "طلب مرتفع جداً. راتب 2,800-3,500 يورو شهرياً", career_opportunities_en: "Very high demand. Salary 2,800-3,500 EUR/month", arab48_notes_ar: "متطلبات قبول معتدلة. فرص عمل مضمونة", arab48_notes_en: "Moderate admission requirements. Guaranteed job opportunities", sort_order: 6 },
    { name_ar: "الطب البيطري", name_en: "Veterinary Medicine", description_ar: "تعرف على دراسة الطب البيطري", description_en: "Learn about veterinary medicine", duration_ar: "11 فصل دراسي", duration_en: "11 semesters", suitable_for_ar: "الطلاب محبي الحيوانات", suitable_for_en: "Animal-loving students", required_background_ar: "بجروت بمعدل 80+ مع تركيز على الأحياء والكيمياء", required_background_en: "Bagrut with GPA 80+ focusing on biology and chemistry", language_requirements_ar: "C1 ألماني إلزامي", language_requirements_en: "C1 German mandatory", career_opportunities_ar: "فرص عمل جيدة. راتب 3,500-4,200 يورو شهرياً", career_opportunities_en: "Good opportunities. Salary 3,500-4,200 EUR/month", arab48_notes_ar: "معدل بجروت 80+ مطلوب. تخصص نادر بين الطلاب العرب", arab48_notes_en: "Bagrut GPA 80+ required. Rare among Arab students", sort_order: 7 },
    { name_ar: "التمريض", name_en: "Nursing", description_ar: "تعرف على مسار التمريض", description_en: "Learn about the nursing pathway", duration_ar: "6 فصول دراسية", duration_en: "6 semesters", suitable_for_ar: "الطلاب الذين يحبون مساعدة الآخرين", suitable_for_en: "Students who love helping others", required_background_ar: "بجروت بمعدل 55+", required_background_en: "Bagrut with GPA 55+", language_requirements_ar: "B2 ألماني إلزامي", language_requirements_en: "B2 German mandatory", career_opportunities_ar: "نقص حاد. فرص عمل مضمونة 100%. راتب 3,000-3,600 يورو", career_opportunities_en: "Severe shortage. 100% guaranteed jobs. Salary 3,000-3,600 EUR", arab48_notes_ar: "أسهل تخصص طبي للقبول. منح وتسهيلات كبيرة", arab48_notes_en: "Easiest medical major for admission. Scholarships available", sort_order: 8 },
  ];

  const engMajors = [
    { name_ar: "هندسة الكمبيوتر", name_en: "Computer Engineering", description_ar: "اجمع بين البرمجيات والهندسة", description_en: "Combine software and engineering", duration_ar: "6 فصول دراسية", duration_en: "6 semesters", suitable_for_ar: "الطلاب الذين يحبون الرياضيات والبرمجة", suitable_for_en: "Students who love math and programming", required_background_ar: "بجروت مع 4-5 وحدات رياضيات وفيزياء", required_background_en: "Bagrut with 4-5 units math and physics", language_requirements_ar: "B2 ألماني لمعظم البرامج", language_requirements_en: "B2 German for most programs", career_opportunities_ar: "شركات مثل SAP, Siemens, BMW. راتب 45,000-55,000 يورو", career_opportunities_en: "Companies like SAP, Siemens, BMW. Salary 45,000-55,000 EUR", arab48_notes_ar: "من أفضل التخصصات. معدل بجروت 70+ كافٍ", arab48_notes_en: "One of the best majors. Bagrut GPA 70+ sufficient", sort_order: 0 },
    { name_ar: "هندسة الطيران", name_en: "Aerospace Engineering", description_ar: "صمم مستقبل الطيران", description_en: "Design the future of aviation", duration_ar: "6 فصول دراسية", duration_en: "6 semesters", suitable_for_ar: "الطلاب الشغوفين بالطيران والفضاء", suitable_for_en: "Students passionate about aviation and space", required_background_ar: "بجروت مع 5 وحدات رياضيات وفيزياء. معدل 75+", required_background_en: "Bagrut with 5 units math and physics. GPA 75+", language_requirements_ar: "B2 ألماني", language_requirements_en: "B2 German", career_opportunities_ar: "Airbus و DLR. راتب 50,000-60,000 يورو", career_opportunities_en: "Airbus and DLR. Salary 50,000-60,000 EUR", arab48_notes_ar: "تخصص مميز بفرص ممتازة. معدل بجروت 75+", arab48_notes_en: "Distinguished major with excellent opportunities. GPA 75+", sort_order: 1 },
    { name_ar: "هندسة الطاقة المتجددة", name_en: "Renewable Energy Engineering", description_ar: "كن جزءًا من مستقبل الطاقة المستدامة", description_en: "Be part of the sustainable energy future", duration_ar: "6 فصول دراسية", duration_en: "6 semesters", suitable_for_ar: "الطلاب المهتمين بالبيئة والاستدامة", suitable_for_en: "Students interested in environment and sustainability", required_background_ar: "بجروت مع 4 وحدات رياضيات", required_background_en: "Bagrut with 4 units math", language_requirements_ar: "B2 ألماني", language_requirements_en: "B2 German", career_opportunities_ar: "Siemens Energy، E.ON. راتب 45,000-55,000 يورو", career_opportunities_en: "Siemens Energy, E.ON. Salary 45,000-55,000 EUR", arab48_notes_ar: "معدل بجروت 65+ كافٍ. تخصص مستقبلي", arab48_notes_en: "Bagrut GPA 65+ sufficient. Future-oriented", sort_order: 2 },
    { name_ar: "هندسة البرمجيات", name_en: "Software Engineering", description_ar: "استعد لبناء أنظمة البرمجيات المتقدمة", description_en: "Build advanced software systems", duration_ar: "6 فصول دراسية", duration_en: "6 semesters", suitable_for_ar: "الطلاب الذين يستمتعون بالبرمجة", suitable_for_en: "Students who enjoy programming", required_background_ar: "بجروت مع 4 وحدات رياضيات", required_background_en: "Bagrut with 4 units math", language_requirements_ar: "B2 ألماني أو IELTS 6.5", language_requirements_en: "B2 German or IELTS 6.5", career_opportunities_ar: "SAP، TeamViewer. راتب 50,000-65,000 يورو", career_opportunities_en: "SAP, TeamViewer. Salary 50,000-65,000 EUR", arab48_notes_ar: "أفضل تخصص لفرص العمل. معدل بجروت 65+ كافٍ", arab48_notes_en: "Best for job opportunities. Bagrut GPA 65+ sufficient", sort_order: 3 },
    { name_ar: "الهندسة الصناعية", name_en: "Industrial Engineering", name_de: "Wirtschaftsingenieurwesen", description_ar: "تعرف على تحسين العمليات", description_en: "Learn about process optimization", duration_ar: "6 فصول دراسية", duration_en: "6 semesters", suitable_for_ar: "الطلاب الذين يريدون الجمع بين الهندسة والإدارة", suitable_for_en: "Students combining engineering and management", required_background_ar: "بجروت مع 4 وحدات رياضيات", required_background_en: "Bagrut with 4 units math", language_requirements_ar: "B2 ألماني", language_requirements_en: "B2 German", career_opportunities_ar: "BMW, Mercedes, McKinsey. راتب 48,000-58,000 يورو", career_opportunities_en: "BMW, Mercedes, McKinsey. Salary 48,000-58,000 EUR", arab48_notes_ar: "معدل بجروت 65+ كافٍ. Wirtschaftsingenieurwesen من أشهر التخصصات", arab48_notes_en: "Bagrut GPA 65+ sufficient. One of Germany's most famous majors", sort_order: 4 },
  ];

  const bizMajors = [
    { name_ar: "إدارة الأعمال", name_en: "Business Administration", description_ar: "أساسيات الإدارة وريادة الأعمال", description_en: "Fundamentals of management and entrepreneurship", duration_ar: "6 فصول دراسية", duration_en: "6 semesters", suitable_for_ar: "الطلاب الطموحين في عالم الأعمال والقيادة", suitable_for_en: "Ambitious students in business and leadership", required_background_ar: "بجروت بمعدل 60+", required_background_en: "Bagrut with GPA 60+", language_requirements_ar: "B2 ألماني. برامج بالإنجليزية متاحة", language_requirements_en: "B2 German. English programs available", career_opportunities_ar: "شركات استشارية، بنوك، شركات كبرى", career_opportunities_en: "Consulting firms, banks, major corporations", arab48_notes_ar: "معدل بجروت 60+ كافٍ. من أسهل التخصصات للقبول", arab48_notes_en: "Bagrut GPA 60+ sufficient. One of easiest for admission", sort_order: 0 },
    { name_ar: "الاقتصاد", name_en: "Economics", description_ar: "فهم الأنظمة الاقتصادية والسياسات", description_en: "Understand economic systems and policies", duration_ar: "6 فصول دراسية", duration_en: "6 semesters", suitable_for_ar: "الطلاب المهتمين بتحليل الأسواق والسياسات الاقتصادية", suitable_for_en: "Students interested in market analysis and economic policy", required_background_ar: "بجروت مع 4 وحدات رياضيات", required_background_en: "Bagrut with 4 units math", language_requirements_ar: "B2 ألماني", language_requirements_en: "B2 German", career_opportunities_ar: "بنوك مركزية، وزارات مالية، مراكز أبحاث", career_opportunities_en: "Central banks, finance ministries, research centers", arab48_notes_ar: "معدل بجروت 65+ كافٍ", arab48_notes_en: "Bagrut GPA 65+ sufficient", sort_order: 1 },
  ];

  const socialMajors = [
    { name_ar: "علم النفس", name_en: "Psychology", description_ar: "دراسة السلوك البشري والعمليات العقلية", description_en: "Study human behavior and mental processes", duration_ar: "6 فصول دراسية", duration_en: "6 semesters", suitable_for_ar: "الطلاب المهتمين بفهم السلوك البشري والصحة النفسية", suitable_for_en: "Students interested in understanding human behavior and mental health", required_background_ar: "بجروت بمعدل 70+", required_background_en: "Bagrut with GPA 70+", language_requirements_ar: "B2-C1 ألماني", language_requirements_en: "B2-C1 German", career_opportunities_ar: "عيادات نفسية، مستشفيات، شركات HR", career_opportunities_en: "Psychology clinics, hospitals, HR companies", arab48_notes_ar: "تخصص مطلوب. معدل بجروت 70+ مطلوب عادةً", arab48_notes_en: "In-demand major. Bagrut GPA 70+ usually required", sort_order: 0 },
    { name_ar: "العلوم السياسية", name_en: "Political Science", description_ar: "فهم الأنظمة السياسية والعلاقات الدولية", description_en: "Understand political systems and international relations", duration_ar: "6 فصول دراسية", duration_en: "6 semesters", suitable_for_ar: "الطلاب المهتمين بالسياسة والعلاقات الدولية", suitable_for_en: "Students interested in politics and international relations", required_background_ar: "بجروت بمعدل 60+", required_background_en: "Bagrut with GPA 60+", language_requirements_ar: "B2 ألماني", language_requirements_en: "B2 German", career_opportunities_ar: "منظمات دولية، صحافة، دبلوماسية", career_opportunities_en: "International organizations, journalism, diplomacy", arab48_notes_ar: "معدل بجروت 60+ كافٍ", arab48_notes_en: "Bagrut GPA 60+ sufficient", sort_order: 1 },
  ];

  const scienceMajors = [
    { name_ar: "الرياضيات", name_en: "Mathematics", description_ar: "عالم الأرقام والنظريات الرياضية", description_en: "The world of numbers and mathematical theories", duration_ar: "6 فصول دراسية", duration_en: "6 semesters", suitable_for_ar: "الطلاب الذين يحبون التفكير المجرد والتحليل الرياضي", suitable_for_en: "Students who love abstract thinking and mathematical analysis", required_background_ar: "بجروت مع 5 وحدات رياضيات", required_background_en: "Bagrut with 5 units math", language_requirements_ar: "B2 ألماني", language_requirements_en: "B2 German", career_opportunities_ar: "بنوك، شركات تأمين، تكنولوجيا، أبحاث أكاديمية", career_opportunities_en: "Banks, insurance, tech, academic research", arab48_notes_ar: "معدل بجروت 70+ مع 5 وحدات رياضيات", arab48_notes_en: "Bagrut GPA 70+ with 5 units math", sort_order: 0 },
    { name_ar: "الفيزياء", name_en: "Physics", description_ar: "فهم قوانين الكون والطبيعة", description_en: "Understand the laws of the universe", duration_ar: "6 فصول دراسية", duration_en: "6 semesters", suitable_for_ar: "الطلاب الفضوليين حول كيفية عمل الكون", suitable_for_en: "Curious students about how the universe works", required_background_ar: "بجروت مع 5 وحدات رياضيات وفيزياء", required_background_en: "Bagrut with 5 units math and physics", language_requirements_ar: "B2 ألماني", language_requirements_en: "B2 German", career_opportunities_ar: "مراكز أبحاث مثل CERN، شركات تكنولوجيا", career_opportunities_en: "Research centers like CERN, tech companies", arab48_notes_ar: "معدل بجروت 70+ مع خلفية رياضيات وفيزياء قوية", arab48_notes_en: "Bagrut GPA 70+ with strong math and physics background", sort_order: 1 },
  ];

  const allMajors = [
    ...healthMajors.map(m => ({ ...m, category_id: catMap["Health & Medical Sciences"] })),
    ...engMajors.map(m => ({ ...m, category_id: catMap["Engineering & Technology"] })),
    ...bizMajors.map(m => ({ ...m, category_id: catMap["Business & Economics"] })),
    ...socialMajors.map(m => ({ ...m, category_id: catMap["Social Sciences & Humanities"] })),
    ...scienceMajors.map(m => ({ ...m, category_id: catMap["Natural Sciences & Mathematics"] })),
  ];

  const { error: majErr } = await supabase.from("majors").insert(allMajors);
  if (majErr) return new Response(JSON.stringify({ error: majErr.message }), { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } });

  return new Response(JSON.stringify({ message: "Seeded successfully", categories: cats!.length, majors: allMajors.length }), { headers: { ...corsHeaders, "Content-Type": "application/json" } });
});
