
-- Migration: Stage 3 DB changes
-- #12: Admin notes for cases
-- #13: Reassignment tracking
-- #19: Referral link uniqueness

ALTER TABLE public.student_cases
  ADD COLUMN IF NOT EXISTS admin_notes text,
  ADD COLUMN IF NOT EXISTS reassigned_from uuid,
  ADD COLUMN IF NOT EXISTS reassignment_notes text,
  ADD COLUMN IF NOT EXISTS reassignment_history jsonb DEFAULT '[]'::jsonb;

-- Add UNIQUE constraint on leads.ref_code (generated by sequence, already unique)
-- First check there are no existing duplicates (the sequence guarantees uniqueness)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'leads_ref_code_unique'
  ) THEN
    -- Only add if no duplicates (skip NULLs since UNIQUE allows multiple NULLs)
    IF NOT EXISTS (
      SELECT ref_code FROM public.leads WHERE ref_code IS NOT NULL
      GROUP BY ref_code HAVING COUNT(*) > 1
    ) THEN
      ALTER TABLE public.leads ADD CONSTRAINT leads_ref_code_unique UNIQUE (ref_code);
    END IF;
  END IF;
END $$;
