-- ═══════════════════════════════════════════════════════════════════════
-- Restore the authenticated SELECT grant on v_cash_debts.
--
-- Background: v_cash_debts (and the settle_cash_collection RPC) were created
-- on the live DB out-of-band and never captured in VCS. The view originally
-- ran with its creator's privileges and bypassed row-level security on the
-- underlying cases/case_payments/rewards — a real leak. A security hardening
-- correctly switched the view to enforce the VIEWER's own RLS (SECURITY
-- INVOKER), but also revoked direct access so only backend (service_role)
-- could SELECT it. That broke the two frontend readers that power the
-- "Cash Collection Debt" KPI:
--   - src/components/admin/MemberDetailDrawer.tsx  (admin viewing a member)
--   - src/pages/team/TeamAnalyticsPage.tsx         (team member, own debts)
-- Both do a direct `.from("v_cash_debts").select()` as the authenticated
-- user, so they silently returned nothing once the grant was pulled.
--
-- Re-granting SELECT to authenticated is now SAFE because the view enforces
-- the viewer's own RLS: a team member only reaches the debts for cases their
-- `cases` RLS lets them read (assigned_to = self), and an admin sees all.
-- RLS — not the grant — is the trust boundary. This restores the KPI without
-- re-opening the leak the hardening closed (the view no longer runs as its
-- creator).
--
-- This migration is idempotent. It does NOT change the view definition (which
-- is not in VCS) or weaken RLS; it only re-issues the SELECT grant the
-- hardening had removed. Apply via `supabase db push` or the dashboard SQL
-- editor (DDL is NOT applied by the Vercel build or ci.yml).
-- ═══════════════════════════════════════════════════════════════════════

GRANT SELECT ON public.v_cash_debts TO authenticated;
