// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izjrprphchilkrgbjmbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6anJwcnBoY2hpbGtyZ2JqbWJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDczNzMsImV4cCI6MjA2NTU4MzM3M30.u2C-07OuMYrWLXh0b47pVxN1PgvLDmef0Au_QsOkrt8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);